[libraries]

lib.files = [
"Homework1/src/HW1Bsp1.vhd",
"Homework1/src/HW1Bsp2.vhd",
"Homework1/src/HW1Bsp3.vhd",
"Uebung4/src/Uebung4_2.vhd",
"Uebung4/src/DFF-tb.vhd",
"Uebung4/src/DFF-ea.vhd",
"Uebung6/src/U61_inertial.vhd",
"Uebung6/src/U61.vhd",
"Uebung1/src/HelloVHDL.vhd",
"Homework3/src/RegFile-ea.vhd",
"Homework3/src/PC-ea.vhd",
"Uebung5/src/Uebung3_1.vhd",
"Uebung5/src/RSFlipFlop-tb.vhd",
"Uebung5/src/Uebung5_2.vhd",
"Uebung5/src/RS-Flipflop-ea.vhd",
"Homework3/src/PC-tb.vhd",
"Homework3/src/SCCPU-p.vhd",
"Homework3/src/Extend-ea.vhd",
"Homework3/src/RegFile-tb.vhd",
"Homework3/src/Extend-tb.vhd",
"Uebung2/src/Uebung2_2.vhd",
"Uebung2/src/Uebung2_1.vhd",
"Uebung2/src/Uebung2_2b.vhd",
"Uebung3/src/FullAdder-ea.vhd",
"Uebung3/src/FullAdder-tb.vhd",
"Uebung3/src/Uebung3_1.vhd",
"Homework2/src/ALU-ea.vhd",
"Homework2/src/FullAdder-ea.vhd",
"Homework2/src/Adder4-tb.vhd",
"Homework2/src/Adder4Report-ea.vhd",
"Homework2/src/ALU-tb.vhd",
"Homework2/src/Adder4-ea.vhd",
]
